
	
	

	  
	#ifndef __GUI_H
	#define __GUI_H
	
	
	#include <mouse.h>
         static Mouse mouse;	
	
	#include <global.h>	
	#include <button.h>
	#include <textbox.h>
	#include <window.h>
	#include <checkbox.h>
	#include <radiobtn.h>
	#include <label.h>
	#include <bitmap.h>
	#include <combobox.h>
	#include <menu.h>
	#include <picbox.h>
	#include <msgbox.h>
	
	MsgBox msgbox;
		
	#include <mouse.cpp>	
	#include <button.cpp>
	#include <textbox.cpp>
	#include <window.cpp>
	#include <checkbox.cpp>
	#include <radiobtn.cpp>
	#include <label.cpp>
	#include <bitmap.cpp>
	#include <combobox.cpp>
	#include <menu.cpp>
	#include <picbox.cpp>
	#include <msgbox.cpp>
	
	
	
		

	#endif // __GUI_H


 	
      
    			


















	

 
